export { HomePage } from './HomePage'
export { ProductsPage } from './ProductsPage'
export { ProductFormPage } from './ProductFormPage'
export { CategoriesPage } from './CategoriesPage'
export { CategoryProductsPage } from './CategoryProductsPage'
export { SellPage } from './SellPage'
export { SalesPage } from './SalesPage'
export { BottlesPage } from './BottlesPage'
